[package]
name = "lin_sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix = {version = "0.2.0", path = "../matrix"}
smurf = "0.2.0"